### PR TITLE
Add tour

### PR DESCRIPTION
**Pull request by ebrahimebrahim**
Adds the tour document that was originally written by Lee in [this google doc](https://docs.google.com/document/d/1msMfBM8JLWvvKMQl4DTWFp4cxCRvWHTtKFNeJltL3i0/edit?usp=sharing).

As markdown we can more easily maintain this documentation

---

Method: It was exported from drive to docx and then to markdown using pandoc with this command:

```sh
pandoc --extract-media . Tour\ of\ VPAW\ Model\ and\ VPAW\ Visualize.docx -o tour_VPAWModel_VPAWVisualize.md --from docx --to gfm
```

### CODE REVIEW

**Review by Leengit — APPROVED** [review]
This looks good, thank you.  Possible further steps:

1. Something about the link on Line 6 of `README.md` isn't right.  I know that that isn't part of this pull request ....
2. In `doc/tour_VPAWModel_VPAWVisualize.md`, there are some strings that could be put between backticks, such as `pediatric_airway_atlas`.  It reads amply well enough as is, so not important.

**Comment by jcfr** [comment]
Consider adding a pre-commit config file with:

```
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier
        types_or: [yaml, markdown, html, css, scss, javascript, json]
        args: [--prose-wrap=always]
```

this will ensure proper formatting of markdown

**Comment by ebrahimebrahim** [comment]
I still need to learn how to do CI properly :sweat_smile:

**Comment by jcfr** [comment]
> how to do CI

For reference:

* https://github.com/KitwareMedical/vpaw/pull/51

**Pull request merged**
