### PR TITLE
ENH: Add SlicerMorph/ImageStacks

### PR DESCRIPTION
**Pull request by jadh4v**
Add SlicerMorph/ImageStacks extension to support reading of image file series of bmp / tiff formats.
Addresses issue #13

### CODE REVIEW

**Comment by andinet** [comment]
Building this PR in Release mode on (**)

Microsoft Visual Studio Community 2022
Version 17.1.4
VisualStudio.17.Release/17.1.4+32407.343
Microsoft .NET Framework
Version 4.8.04084

results in compilation error (*)






PS

(*)

2>D:\b\VPAWR22\VTK-build\Rendering\OpenGL2\vtkRenderingOpenGL2Module.h(42,10): fatal error C1083: Cannot open include file: 'vtkRenderingHyperTreeGridModule.h': No such file or directory (compiling source file D:\b\VPAWR22\iMSTK\Source\RenderingVTK\RenderDelegate\imstkVTKFluidRenderDelegate.cpp) [D:\b\VPAWR22\imstk-build\Source\RenderingVTK\RenderingVTK.vcxproj]
42>  imstkVTKLineMeshRenderDelegate.cpp
42>  imstkVTKOrientedBoxRenderDelegate.cpp
42>D:\b\VPAWR22\VTK-build\Rendering\OpenGL2\vtkRenderingOpenGL2Module.h(42,10): fatal error C1083: Cannot open include file: 'vtkRenderingHyperTreeGridModule.h': No such file or directory (compiling source file D:\b\VPAWR22\iMSTK\Source\RenderingVTK\imstkVTKRenderer.cpp) [D:\b\VPAWR22\imstk-build\Source\RenderingVTK\RenderingVTK.vcxproj]
42>  imstkVTKPlaneRenderDelegate.cpp
42>  imstkVTKPointSetRenderDelegate.cpp
42>  imstkVTKPolyDataRenderDelegate.cpp
42>  imstkVTKRenderDelegate.cpp
42>  imstkVTKSphereRenderDelegate.cpp
42>  imstkVTKSurfaceMeshRenderDelegate.cpp
42>  imstkVTKSurfaceNormalRenderDelegate.cpp
42>D:\b\VPAWR22\VTK-build\Rendering\OpenGL2\vtkRenderingOpenGL2Module.h(42,10): fatal error C1083: Cannot open include file: 'vtkRenderingHyperTreeGridModule.h': No such file or directory (compiling source file D:\b\VPAWR22\iMSTK\Source\RenderingVTK\RenderDelegate\imstkVTKLineMeshRenderDelegate.cpp) [D:\b\VPAWR22\imstk-build\Source\RenderingVTK\RenderingVTK.vcxproj]
42>  imstkVTKTetrahedralMeshRenderDelegate.cpp
42>D:\b\VPAWR22\VTK-build\Rendering\OpenGL2\vtkRenderingOpenGL2Module.h(42,10): fatal error C1083: Cannot open include file: 'vtkRenderingHyperTreeGridModule.h': No such file or directory (compiling source file D:\b\VPAWR22\iMSTK\Source\RenderingVTK\RenderDelegate\imstkVTKPointSetRenderDelegate.cpp) [D:\b\VPAWR22\imstk-build\Source\RenderingVTK\RenderingVTK.vcxproj]
42>  imstkVTKVolumeRenderDelegate.cpp
42>D:\b\VPAWR22\VTK-build\Rendering\OpenGL2\vtkRenderingOpenGL2Module.h(42,10): fatal error C1083: Cannot open include file: 'vtkRenderingHyperTreeGridModule.h': No such file or directory (compiling source file D:\b\VPAWR22\iMSTK\Source\RenderingVTK\RenderDelegate\imstkVTKSurfaceMeshRenderDelegate.cpp) [D:\b\VPAWR22\imstk-build\Source\RenderingVTK\RenderingVTK.vcxproj]
42>D:\b\VPAWR22\VTK-build\Rendering\OpenGL2\vtkRenderingOpenGL2Module.h(42,10): fatal error C1083: Cannot open include file: 'vtkRenderingHyperTreeGridModule.h': No such file or directory (compiling source file D:\b\VPAWR22\iMSTK\Source\RenderingVTK\RenderDelegate\imstkVTKSurfaceNormalRenderDelegate.cpp) [D:\b\VPAWR22\imstk-build\Source\RenderingVTK\RenderingVTK.vcxproj]
42>  Building Custom Rule D:/b/VPAWR22/iMSTK/Source/ViewerCore/CMakeLists.txt







(**)


Microsoft Visual Studio Community 2022
Version 17.1.4
VisualStudio.17.Release/17.1.4+32407.343
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Visual C++ 2022   00482-90000-00000-AA257
Microsoft Visual C++ 2022

ASP.NET and Web Tools 2019   17.1.358.51495
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   17.1.358.51495
Azure App Service Tools v3.0.0

C# Tools   4.1.0-5.22165.10+e555772db77ca828b02b4bd547c318387f11d01f
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   17.0.21344.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   6.1.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

NVIDIA CUDA 11.7 Wizards   11.7
Wizards to create new NVIDIA CUDA projects and source files.

NVIDIA Nsight Visual Studio Edition   2022.2.0.22095
NVIDIA Nsight Visual Studio Edition provides tools for GPGPU and graphics development.  Copyright © NVIDIA 2010 - 2022.
•Direct3D® and DirectX® are registered trademarks of Microsoft Corporation in the United States and/or other countries.
•Microsoft Detours is used under the Professional license (http://research.microsoft.com/en-us/projects/detours/).
•Gardens Point Parser Generator Copyright 2005 Queensland University of Technology (QUT). All rights reserved.
•Icons from Axialis Software used under the licensing terms found here: www.axialis.com
•NLog Copyright © 2004-2006 Jaroslaw Kowalski (jaak@jkowalski.net)
•zlib and libpng used under the zlib/libpnc license (http://opensource.org/licenses/Zlib) 
•Breakpad Copyright ©2006, Google Inc. All rights reserved.
•The OpenGL Extension Wrangler Library
Copyright ©2008-2016, Nigel Stewart (nigels@users.sourceforge.net), Copyright ©2002-2008, Milan Ikits (milan.ikits@ieee.org), Copyright ©2002-2008, Marcelo E. Magallon (mmagallo@debian.org), Copyright ©2002, Lev Povalahev. 
All rights reserved. 
•LIBSSH2 Copyright ©2004-2007 Sara Golemon (sarag@libssh2.org), Copyright ©2005,2006 Mikhail Gusarov (dottedmag@dottedmag.net),Copyright ©2006-2007 The Written Word, Inc.,Copyright ©2007 Eli Fant (elifantu@mail.ru),Copyright ©2009-2014 Daniel Stenberg., Copyright ©2008, 2009 Simon Josefsson.
All rights reserved. 
•Protobuf Copyright ©2014, Google Inc. All rights reserved.
•xxHASH Library Copyright ©2012-2014, Yann Collet. All rights reserved. 
•FMT Copyright ©2012 - 2016, Victor Zverovich 
•Font Awesome Copyright 2018 Fonticons, Inc. 
•ELF Definitions Copyright (c) 2010 Joseph Koshy, All rights reserved.

Warning: This computer program is protected by copyright law and international treaties. Unauthorized reproduction or distribution of this program, or any portion of it, may result in severe civil and criminal penalties, and will be prosecuted to the maximum extent possible under the law.

NVIDIA Nsight Visual Studio Edition - CUDA support   2022.2.0.22095
NVIDIA Nsight Visual Studio Edition - CUDA support provides tools for CUDA development and debugging.

Python - Django support   17.0.21344.1
Provides templates and integration for the Django web framework.

Python - Profiling support   17.0.21344.1
Profiling support for Python projects.

Python - VC Project Support   17.0.21344.1
Provides support for launching C++ projects with Python debugging enabled.

Python with Pylance   17.0.21344.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   17.0.1229.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.1.0-5.22165.10+e555772db77ca828b02b4bd547c318387f11d01f
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

**Comment by jadh4v** [comment]
Thanks, I will try a clean build and see if I can re-create these errors.

**Comment by jadh4v** [comment]
My build ran successfully. I cannot re-create this compiler error.
@andinet can you confirm that you are using the correct git SHA 82b59ca?

**Review by jcfr — APPROVED** [review]

**Comment by jadh4v** [comment]
@andinet Were you able to build this again?

**Comment by jcfr** [comment]
Considering that (1) the module `ImageStacks` is pure python and (2) @jadh4v local build is :heavy_check_mark: , the reported errors [^1] are not related to this pull request and integrating is sensible.

[^1]: https://github.com/KitwareMedical/vpaw/pull/17#issuecomment-1214195766

References:
* https://github.com/SlicerMorph/SlicerMorph/tree/master/ImageStacks
* https://github.com/SlicerMorph/SlicerMorph/blob/master/ImageStacks/CMakeLists.txt

**Pull request merged**
